### ISSUE TITLE
Error: Cannot find module './buildSchema'

### ISSUE THREAD

**Issue by kriswallsmith** [dpeek/dgraphql#18]
I'm getting this error when I try to run something similar to the example. Apologies if this if a support request and not a bug report… I could certainly be doing something wrong. Thank you!

Here's my `server.js`:

```javascript
#!/usr/bin/env node
const path = require('path');
const fs = require('fs');
const express = require('express');
const graphqlHTTP = require('express-graphql');
const { Client } = require('dgraphql');

const schema = path.resolve(__dirname, 'data', 'schema.graphql');
const client = new Client({
  server: 'http://localhost:8080/query',
  schema: fs.readFileSync(schema, 'utf-8'),
});

const app = express();
app.use('/', graphqlHTTP((req, res) => {
  const lang = req.headers['accept-language'].split('-')[0];

  return {
    schema: client.schema,
    context: client.getContext(lang),
    graphiql: true,
  };
}));
app.listen(4000);
```

Here's the output:

```
$ ./server.js 
module.js:487
    throw err;
    ^

Error: Cannot find module './buildSchema'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (.../node_modules/dgraphql/lib/client.js:18:20)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

And here's my `package.json`:

```javascript
{
  "dependencies": {
    "dgraphql": "^0.4.0",
    "express": "^4.15.3",
    "express-graphql": "^0.6.6",
    "graphql": "^0.10.3"
  }
}
```

**Comment by dpeek** [comment]
Can I ask what version of node you're using? I've released a few changes in the last days, could you get the latest and test again?

In an empty directory, this works for me:

```bash
npm init -y
npm i --save express express-graphql dgraphql
```

In `index.js`

```javascript
const path = require("path");
const fs = require("fs");
const express = require("express");
const graphqlHTTP = require("express-graphql");
const { Client } = require("dgraphql");

const schema = path.resolve(__dirname, "data", "schema.graphql");
const client = new Client({
  server: "http://localhost:8080/query",
  schema: `
  type Person {
    id: ID!
    name: String
  }
  `
});

const app = express();
app.use(
  "/",
  graphqlHTTP((req, res) => {
    const lang = req.headers["accept-language"].split("-")[0];

    return {
      schema: client.schema,
      context: client.getContext(lang),
      graphiql: true
    };
  })
);
app.listen(4000);
```

And then:

```bash
node index.js
```

**Comment by dpeek** [comment]
Closing this for now, let me know if you still have issues.
